name: Auto Assign New Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Auto‑assign issue
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: Rafal-Chrzanowski, Dorota-Laczak
          numOfAssignees: 0  # 0 = all
